version: '3'

services:
  web-ui:
    build: https://github.com/Boyannik7/CovidWebApp-front-end.git#main
    depends_on:
      - server
    ports:
      - "80:80"
    networks: 
      - external-net
      - internal-net
    configs:
      - httpd-config
    secrets:
      - server-certificate

  server:
    build: https://github.com/Boyannik7/CovidWebApp-server.git#main
    container_name: server
    depends_on:
      - ml-script
      - dataset-data
    networks:
      - internal-net
    volumes:
      - internal-vol:/app/data
    environment: 
      - INPUT_DATA_FILE_NAME=/data/input_data
      - OUTPUT_DATA_FILE_NAME=/data/output_data
      - PY_SCRIPT_URL=ml-script
      - DIAGRAM_VALUES_STEP=5000
      - DIAGRAM_VALUES_LIMIT=30000
      - RATE_LIMIT_PER_HOUR=300

  ml-script:
    build: https://github.com/Boyannik7/CovidWebApp-ML.git#main
    container_name: ml-script
    depends_on:
      - dataset-data
    networks:
      - internal-net
    volumes:
      - internal-vol:/data

  dataset-data:
    image: radito3/covid-datasets:v1
    volumes:
      - internal-vol:/data

configs:
  httpd-config:
    external: true

secrets:
  server-certificate:
    external: true

networks:
  internal-net:
    driver: bridge
  external-net:

volumes:
  internal-vol:
